/**
 * Design tokens and shared style objects. Colors and type come from a
 * single frozen source so every component stays visually consistent.
 * Style values are plain data, exported for inline use by components.
 */

export const C = Object.freeze({
  paper: "#F2F3EE",
  panel: "#FFFFFF",
  ink: "#1A2018",
  inkMuted: "#5A6355",
  olive: "#3E4A2E",
  oliveSoft: "#E9ECE2",
  line: "#D8DCD0",
  orange: "#E05A0C",
  success: "#2E7D32",
  miss: "#B3261E",
  noAttempt: "#B98A00",
});

export const DISPLAY = "'Barlow Condensed', 'Arial Narrow', sans-serif";
export const BODY = "'Barlow', 'Segoe UI', system-ui, sans-serif";
export const MONO = "'IBM Plex Mono', ui-monospace, 'Courier New', monospace";

/** @returns {object} A status pill style tinted for the given color. */
export function pillStyle(color) {
  return {
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: 999,
    fontFamily: DISPLAY,
    fontWeight: 600,
    fontSize: 12,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color,
    border: `1.5px solid ${color}`,
    background: "transparent",
    whiteSpace: "nowrap",
  };
}

export const st = Object.freeze({
  page: {
    maxWidth: 760,
    margin: "0 auto",
    padding: "0 16px 96px",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "18px 0 14px",
    borderBottom: `2px solid ${C.ink}`,
    marginBottom: 18,
    flexWrap: "wrap",
  },
  brand: {
    fontFamily: DISPLAY,
    fontWeight: 700,
    fontSize: 30,
    lineHeight: 1,
    letterSpacing: "0.02em",
    textTransform: "uppercase",
    color: C.ink,
    margin: 0,
  },
  brandSub: {
    fontFamily: MONO,
    fontSize: 11,
    color: C.inkMuted,
    letterSpacing: "0.04em",
    marginTop: 4,
  },
  roleRow: { display: "flex", alignItems: "center", gap: 10 },
  card: {
    background: C.panel,
    border: `1px solid ${C.line}`,
    borderRadius: 12,
    padding: 18,
    marginBottom: 16,
  },
  secHead: {
    fontFamily: DISPLAY,
    fontWeight: 700,
    fontSize: 20,
    letterSpacing: "0.03em",
    textTransform: "uppercase",
    color: C.olive,
    margin: "0 0 12px",
  },
  label: {
    display: "block",
    fontFamily: DISPLAY,
    fontWeight: 600,
    fontSize: 13,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: C.inkMuted,
    marginBottom: 5,
  },
  input: {
    width: "100%",
    minHeight: 44,
    padding: "10px 12px",
    fontFamily: BODY,
    fontSize: 16,
    color: C.ink,
    background: C.panel,
    border: `1.5px solid ${C.line}`,
    borderRadius: 8,
    outline: "none",
  },
  mono: { fontFamily: MONO },
  field: { display: "flex", flexDirection: "column", marginBottom: 14 },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  priBtn: {
    minHeight: 48,
    padding: "12px 20px",
    fontFamily: DISPLAY,
    fontWeight: 700,
    fontSize: 17,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: C.panel,
    background: C.olive,
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
  },
  ghostBtn: {
    minHeight: 44,
    padding: "8px 16px",
    fontFamily: DISPLAY,
    fontWeight: 600,
    fontSize: 14,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: C.ink,
    background: "transparent",
    border: `1.5px solid ${C.line}`,
    borderRadius: 8,
    cursor: "pointer",
  },
  dangerBtn: {
    minHeight: 40,
    padding: "6px 14px",
    fontFamily: DISPLAY,
    fontWeight: 600,
    fontSize: 13,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: C.miss,
    background: "transparent",
    border: `1.5px solid ${C.miss}`,
    borderRadius: 8,
    cursor: "pointer",
  },
  doneBtn: {
    width: "100%",
    minHeight: 56,
    fontFamily: DISPLAY,
    fontWeight: 700,
    fontSize: 20,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: C.panel,
    background: C.orange,
    border: "none",
    borderRadius: 10,
    cursor: "pointer",
  },
  tabBar: {
    position: "sticky",
    top: 0,
    zIndex: 5,
    display: "flex",
    gap: 4,
    overflowX: "auto",
    background: C.paper,
    borderBottom: `1px solid ${C.line}`,
    margin: "0 0 18px",
    padding: "6px 0",
  },
  tab: {
    flex: "0 0 auto",
    minHeight: 44,
    padding: "8px 16px",
    fontFamily: DISPLAY,
    fontWeight: 600,
    fontSize: 15,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: C.inkMuted,
    background: "transparent",
    border: "none",
    borderBottom: "3px solid transparent",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  tabActive: {
    color: C.ink,
    borderBottom: `3px solid ${C.orange}`,
  },
  strip: {
    display: "grid",
    gridTemplateColumns: "repeat(5, 1fr)",
    background: C.ink,
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 18,
  },
  stripCell: {
    padding: "12px 8px",
    textAlign: "center",
    borderRight: `1px solid rgba(255,255,255,0.08)`,
  },
  stripLabel: {
    fontFamily: DISPLAY,
    fontWeight: 600,
    fontSize: 10,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "rgba(242,243,238,0.6)",
    marginBottom: 4,
  },
  stripValue: {
    fontFamily: MONO,
    fontWeight: 500,
    fontSize: 22,
    lineHeight: 1,
    color: C.paper,
  },
  outcomeRow: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 8 },
  outcomeBtn: {
    minHeight: 76,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    fontFamily: DISPLAY,
    fontWeight: 700,
    fontSize: 16,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    background: C.panel,
    border: `2px solid ${C.line}`,
    borderRadius: 10,
    color: C.inkMuted,
    cursor: "pointer",
  },
  rowItem: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    padding: "12px 0",
    borderBottom: `1px solid ${C.line}`,
  },
  meta: { fontFamily: MONO, fontSize: 12, color: C.inkMuted },
  notice: {
    padding: "12px 14px",
    borderRadius: 8,
    fontSize: 14,
    marginBottom: 14,
  },
  error: {
    color: C.miss,
    fontFamily: MONO,
    fontSize: 13,
    marginTop: 8,
  },
});
